modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="elementals"
version="1.2.0"
displayName="Elementals"
displayURL="https://meherbensalem.github.io"
logoFile="logo.png"
credits="no credits"
authors="NAIZO"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.elementals]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementals]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.elementals]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.elementals]]
    modId="playeranimator"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.elementals]]
    modId="jauml"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration